name: client
description: Remote Configuration Util for Living Room PCs
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.0
  shared_preferences: ^0.5.10
  json_annotation: ^3.0.0
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  rxdart: ^0.24.1
  flutter_svg: ^0.18.1
  fl_chart: ^0.11.1
  byte_size: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.4.0

flutter:
  uses-material-design: true
