[package]
name = "remote-desktop-configuration-server"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
libpulse-binding = { version = "2", no_default_features = true, features = ["pa_latest"] }
rust-pulsectl = { git = "https://github.com/maxjoehnk/pulsectl" }
bluez = "0.1"
async-std = { version = "1.6", features = ["attributes"] }
tide = "0.13"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
linicon = "2"
evdev = "0.10"
evdev-rs = "0.4.0"
surf = "2.0.0-alpha.4"
sensors = "0.2"
psutil = "3.1"
pinboard = "2"
lazy_static = "1.4"
